name: ساخت خودکار APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: دریافت کد پروژه
        uses: actions/checkout@v4

      - name: نصب جاوا ۱۷
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: اجازه اجرا به gradlew
        run: chmod +x gradlew

      - name: ساخت APK نسخه دیباگ
        run: ./gradlew assembleDebug --stacktrace

      - name: آپلود APK به‌عنوان خروجی قابل دانلود
        uses: actions/upload-artifact@v4
        with:
          name: AlarmDaroo-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
